### ISSUE TITLE
ERROR: Service 'flarum' failed to build

### ISSUE THREAD

**Issue by thelmosantos** [spujadas/flarum-docker#3]
Hi!
I am getting this error when I tried to deploy the docker:

[root@server flarum]# docker-compose up -d
Building flarum
Step 1/50 : FROM phusion/baseimage
 ---> 166cfc3f6974
Step 2/50 : MAINTAINER Sebastien Pujadas http://pujadas.net
 ---> Using cache
 ---> ac9802ee9bd3
Step 3/50 : ENV REFRESHED_AT 2015-05-12
 ---> Using cache
 ---> fc2e863bab6b
Step 4/50 : RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C  && add-apt-repository -y ppa:ondrej/php5-5.6  && apt-key update  && apt-get update -qq
 ---> Running in 1f162a8f3585
Executing: /tmp/tmp.cwrSCWSntM/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
4F4EA0AAE5267A6C
gpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com
gpg: key E5267A6C: public key "Launchpad PPA for Ondřej Surý" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Cannot add PPA: 'ppa:~ondrej/ubuntu/php5-5.6'.
The user named '~ondrej' has no PPA named 'ubuntu/php5-5.6'
Please choose from the following available PPAs:
 * 'apache2':  PPA for Apache 2.x
 * 'apache2-qa':  PPA for Apache2 (QA builds; experimental)
 * 'autotools':  PPA for autotools (not-supported; build-dependency; experimental)
 * 'bind9':  PPA for BIND 9
 * 'cmake':  PPA for CMake (not-supported, experimental)
 * 'common':  Common PPA packages
 * 'cyrus-imapd':  PPA for Cyrus IMAP
 * 'debhelper':  PPA for Debhelper (and friends)
 * 'golang':  PPA for Go (experimental, build-dependency)
 * 'llvm':  PPA for LLVM
 * 'mariadb-10.0':  PPA for MariaDB 10.0 (don't use, broken)
 * 'mysql-5.5':  PPA for MySQL 5.5 (don't use, broken)
 * 'mysql-5.6':  PPA for MySQL 5.6 (don't use, broken)
 * 'mysql-5.7':  PPA for MySQL 5.7 (don't use, broken)
 * 'nginx':  PPA for NGINX Stable with HTTP/2
 * 'nginx-mainline':  PPA for NGINX Mainline with HTTP/2
 * 'nginx-qa':  PPA for NGINX Mainline (QA builds; experimental)
 * 'pelican':  PPA for Pelican
 * 'php':  ***** The main PPA for supported PHP versions with many PECL extensions *****
 * 'php-qa':  PPA for PHP (QA builds; experimental)
 * 'php-zts':  PPA for PHP ZTS (experimental, unsupported)
 * 'php5-compat':  PPA with dummy compatibility php5* packages
 * 'pkg-dpkg':  dpkg and friends (very experimental)
 * 'pkg-gearman':  PPA for Gearman
 * 'pkg-nlnetlabs':  NLNetLabs Backported Packages
 * 'sandbox':  Sandbox for preparation of various packages (DON'T USE)
 * 'seafile':  PPA for Seafile
 * 'unbound':  PPA for Unbound (mainly a build-dep)
 * 'zonemaster':  PPA for Zonemaster
**ERROR: Service 'flarum' failed to build: The command '/bin/sh -c apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C  && add-apt-repository -y ppa:ondrej/php5-5.6  && apt-key update  && apt-get update -qq' returned a non-zero code: 1**

Any idea what I am doing wrong?

Thanks and BR,

**Comment by spujadas** [comment]
I would recommend against using this repo, which I haven't touched in over 4 years (and not planning to update in future) and is severely outdated.
FWIW the error basically says the private apt repository which I used at the time to install PHP 5.6 no longer exists (see e.g. https://stackoverflow.com/questions/40567133/cannot-add-ppa-ppaondrej-php5-5-6).
If you _really_ want to build a Docker image for Flarum, then _maybe_ you can use the existing repo and try adapting everything (starting with the `Dockerfile`) to the latest requirements and installation instructions from https://flarum.org/docs/install.html… but it may be a thankless task tbh.
Best of luck.
